print(" ","¨¨"*28)
print('Seja bem vindo ao gerador de nome de bandas')
cidade = input('Primeiro me conte, em qual cidade nasceu ?\n >: ')
mascote = input('Agora preciso saber qual o nome do seu animal de estimação?\n >: ')
print(f'Bom o nome da sua banda poderia ser: {mascote} {cidade}, \nDivirta-se!')
print("\n","¨¨"*28)